// DATOS DE DEMOSTRACIÓN — no son inmuebles reales. Se usan solo cuando no hay base de datos
// configurada (modo demostración) y siempre se muestran con la etiqueta "Demostración".
import type { CatalogListing, CatalogMedia, CatalogPrice } from "../catalog/types";

const base = {
  country: "República Dominicana",
  condition: null,
  status: "publicado" as const,
  available_from: null,
  is_demo: true,
  is_maj_listing: true,
  public_address: null,
  floor_number: null,
  levels: null,
  year_built: null,
  half_bathrooms: null,
  service_room: "desconocido" as const,
  service_bathroom: "desconocido" as const,
  laundry_area: "desconocido" as const,
  balcony: "desconocido" as const,
  terrace: "desconocido" as const,
  patio: "desconocido" as const,
  roof_area: "desconocido" as const,
  roof_use_detail: null,
  na_fields: [] as string[],
  condo_rules: null,
  restrictions: null,
  documents_reviewed_at: null,
  documents_review_scope: null,
  sale_price: null,
  sale_currency: null,
  sale_negotiable: null,
  rent_price: null,
  rent_currency: null,
  rent_negotiable: null,
  rent_period: null,
  cover_path: null,
  cover_alt: "Imagen ilustrativa de demostración",
  advisor_name: null,
  advisor_whatsapp: null,
  photo_count: 0,
  updated_at: "2026-10-01T15:00:00Z",
  published_at: "2026-10-01T15:00:00Z",
};

export const demoListings: CatalogListing[] = [
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000001",
    code: "DEMO-000001",
    slug: "demo-apartamento-en-sector-urbano",
    title: "DEMO · Apartamento de 3 habitaciones en zona urbana",
    operation: "venta",
    property_type: "apartamento",
    description:
      "Publicación de demostración para revisar el diseño. No corresponde a un inmueble real. Muestra cómo se presentan los datos en cajas separadas, el precio en su moneda original y la ubicación aproximada.",
    condition: "nuevo",
    province: "Distrito Nacional",
    municipality: "Santo Domingo de Guzmán",
    sector: "Sector de ejemplo",
    approx_lat: "18.470",
    approx_lng: "-69.940",
    built_area_m2: "165.00",
    land_area_m2: null,
    bedrooms: 3,
    bathrooms: 3,
    half_bathrooms: 1,
    parking_spaces: 2,
    floor_number: 7,
    service_room: "si",
    balcony: "si",
    laundry_area: "si",
    features: {
      ascensor: { v: "si" },
      planta_electrica: { v: "si", d: "Cobertura total" },
      cisterna: { v: "si" },
      piscina: { v: "no" },
      gimnasio: { v: "si" },
      seguridad: { v: "si", d: "24 horas" },
      mascotas: { v: "desconocido" },
    },
    sale_price: "285000.00",
    sale_currency: "USD",
    sale_negotiable: true,
    photo_count: 1,
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000002",
    code: "DEMO-000002",
    slug: "demo-casa-familiar",
    title: "DEMO · Casa familiar con patio",
    operation: "ambas",
    property_type: "casa",
    description: "Ejemplo de inmueble disponible en venta y renta, con precios independientes en monedas distintas. No es un inmueble real.",
    condition: "usado",
    province: "Santiago",
    municipality: "Santiago de los Caballeros",
    sector: "Sector de ejemplo",
    approx_lat: "19.450",
    approx_lng: "-70.690",
    built_area_m2: "240.00",
    land_area_m2: "400.00",
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 3,
    levels: 2,
    patio: "si",
    terrace: "si",
    na_fields: ["floor_number"],
    features: { inversor: { v: "si" }, tinaco: { v: "si" }, cisterna: { v: "si" }, mascotas: { v: "si" } },
    sale_price: "12500000.00",
    sale_currency: "DOP",
    sale_negotiable: false,
    rent_price: "65000.00",
    rent_currency: "DOP",
    rent_negotiable: false,
    rent_period: "mensual",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000003",
    code: "DEMO-000003",
    slug: "demo-solar-residencial",
    title: "DEMO · Solar residencial",
    operation: "venta",
    property_type: "solar",
    description: "Ejemplo de terreno: no se piden habitaciones ni baños porque no aplican. No es un inmueble real.",
    province: "La Altagracia",
    municipality: "Higüey",
    sector: "Sector de ejemplo",
    approx_lat: "18.610",
    approx_lng: "-68.710",
    built_area_m2: null,
    land_area_m2: "1200.00",
    bedrooms: null,
    bathrooms: null,
    parking_spaces: null,
    na_fields: ["built_area_m2", "bedrooms", "bathrooms", "half_bathrooms", "floor_number", "levels", "year_built"],
    features: { agua: { v: "si", d: "Acueducto" } },
    sale_price: "95000.00",
    sale_currency: "USD",
    sale_negotiable: true,
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000004",
    code: "DEMO-000004",
    slug: "demo-apartamento-amueblado-en-renta",
    title: "DEMO · Apartamento amueblado en renta",
    operation: "renta",
    property_type: "apartamento",
    description: "Ejemplo de renta con mantenimiento, depósito y plazo mínimo. No es un inmueble real.",
    condition: "remodelado",
    province: "Santo Domingo",
    municipality: "Santo Domingo Este",
    sector: "Sector de ejemplo",
    approx_lat: "18.490",
    approx_lng: "-69.860",
    built_area_m2: "95.00",
    land_area_m2: null,
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    floor_number: 4,
    balcony: "si",
    features: { amueblado: { v: "si", d: "Total" }, aire_acondicionado: { v: "si", d: "Habitaciones" }, ascensor: { v: "si" }, mascotas: { v: "no" } },
    rent_price: "1300.00",
    rent_currency: "USD",
    rent_negotiable: false,
    rent_period: "mensual",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000005",
    code: "DEMO-000005",
    slug: "demo-local-comercial",
    title: "DEMO · Local comercial en avenida",
    operation: "renta",
    property_type: "local",
    description: "Ejemplo de local comercial. No es un inmueble real.",
    province: "Distrito Nacional",
    municipality: "Santo Domingo de Guzmán",
    sector: "Sector de ejemplo",
    approx_lat: "18.480",
    approx_lng: "-69.920",
    built_area_m2: "120.00",
    land_area_m2: null,
    bedrooms: null,
    bathrooms: 1,
    parking_spaces: 4,
    na_fields: ["bedrooms"],
    features: { planta_electrica: { v: "si", d: "Áreas comunes" }, seguridad: { v: "desconocido" } },
    rent_price: "95000.00",
    rent_currency: "DOP",
    rent_negotiable: true,
    rent_period: "mensual",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000006",
    code: "DEMO-000006",
    slug: "demo-villa-de-playa",
    title: "DEMO · Villa con piscina",
    operation: "venta",
    property_type: "villa",
    description: "Ejemplo de villa. No es un inmueble real.",
    condition: "nuevo",
    province: "Puerto Plata",
    municipality: "Sosúa",
    sector: "Sector de ejemplo",
    approx_lat: "19.750",
    approx_lng: "-70.520",
    built_area_m2: "380.00",
    land_area_m2: "900.00",
    bedrooms: 5,
    bathrooms: 5,
    half_bathrooms: 1,
    parking_spaces: 4,
    levels: 2,
    terrace: "si",
    patio: "si",
    na_fields: ["floor_number"],
    features: { piscina: { v: "si" }, planta_electrica: { v: "si", d: "Total" }, amueblado: { v: "no" } },
    sale_price: "690000.00",
    sale_currency: "USD",
    sale_negotiable: false,
  },
];

export function demoPrices(id: string): CatalogPrice[] {
  const l = demoListings.find((x) => x.id === id);
  if (!l) return [];
  const out: CatalogPrice[] = [];
  const common = {
    property_id: id,
    maintenance_amount: null,
    maintenance_currency: null,
    maintenance_included: "desconocido" as const,
    additional_costs: null,
    deposit_amount: null,
    deposit_months: null,
    advance_months: null,
    min_term_months: null,
    delivery_conditions: null,
  };
  if (l.sale_currency)
    out.push({ ...common, operation: "venta", amount: l.sale_price, currency: l.sale_currency, negotiable: !!l.sale_negotiable, rent_period: null });
  if (l.rent_currency)
    out.push({
      ...common,
      operation: "renta",
      amount: l.rent_price,
      currency: l.rent_currency,
      negotiable: !!l.rent_negotiable,
      rent_period: l.rent_period,
      maintenance_amount: l.id.endsWith("4") ? "4500.00" : null,
      maintenance_currency: l.id.endsWith("4") ? "DOP" : null,
      maintenance_included: l.id.endsWith("4") ? "no" : "desconocido",
      deposit_months: "2.0",
      advance_months: "1.0",
      min_term_months: 12,
    });
  return out;
}

export function demoMedia(): CatalogMedia[] {
  return [];
}
